"""
FILE: app/schemas.py
PURPOSE: Defines the shape of data coming IN (requests) and going OUT (responses).

Pydantic schemas are like "contracts" for your API:
  - They validate incoming request data automatically
  - They define exactly what your API returns
  - They generate the documentation in Swagger UI

Think of it like this:
  - models.py  → what the DATABASE looks like (SQLAlchemy)
  - schemas.py → what the API INPUT/OUTPUT looks like (Pydantic)

We use separate schemas for Create, Update, and Response
because the data shape is different in each case.
"""

from datetime import datetime
from typing import Optional, Literal
from pydantic import BaseModel, Field, field_validator


# ─────────────────────────────────────────────────────────────
# ALLOWED VALUES
# ─────────────────────────────────────────────────────────────

# We restrict environments to these three values only
# If someone sends "production" or "PROD", it will be rejected automatically
EnvironmentType = Literal["dev", "staging", "prod"]


# ─────────────────────────────────────────────────────────────
# CREATE SCHEMA — used when POST /configs is called
# ─────────────────────────────────────────────────────────────

class ConfigCreate(BaseModel):
    """
    Schema for creating a new configuration.
    
    This is what the API caller must send in the request body.
    
    Example JSON:
    {
        "service_name": "payment-service",
        "environment": "prod",
        "key": "DB_HOST",
        "value": "payment-db.internal"
    }
    """

    service_name: str = Field(
        ...,                          # '...' means this field is REQUIRED
        min_length=1,
        max_length=100,
        description="Name of the service (e.g., payment-service)",
        examples=["payment-service"]
    )

    environment: EnvironmentType = Field(
        ...,
        description="Target environment: dev, staging, or prod",
        examples=["prod"]
    )

    key: str = Field(
        ...,
        min_length=1,
        max_length=200,
        description="Configuration key (e.g., DB_HOST)",
        examples=["DB_HOST"]
    )

    value: str = Field(
        ...,
        min_length=1,
        description="Configuration value (e.g., payment-db.internal)",
        examples=["payment-db.internal"]
    )

    @field_validator("service_name")
    @classmethod
    def service_name_lowercase(cls, v: str) -> str:
        """Automatically convert service_name to lowercase for consistency"""
        return v.strip().lower()

    @field_validator("key")
    @classmethod
    def key_uppercase(cls, v: str) -> str:
        """Automatically convert key to UPPERCASE for consistency (like env vars)"""
        return v.strip().upper()


# ─────────────────────────────────────────────────────────────
# UPDATE SCHEMA — used when PUT /configs/{id} is called
# ─────────────────────────────────────────────────────────────

class ConfigUpdate(BaseModel):
    """
    Schema for updating an existing configuration.
    
    All fields are OPTIONAL — you can update just the value,
    or just the environment, or both, etc.
    
    Example JSON (update only the value):
    {
        "value": "new-payment-db.internal"
    }
    """

    value: Optional[str] = Field(
        None,
        min_length=1,
        description="New value for the configuration",
        examples=["new-payment-db.internal"]
    )

    environment: Optional[EnvironmentType] = Field(
        None,
        description="New environment: dev, staging, or prod"
    )


# ─────────────────────────────────────────────────────────────
# RESPONSE SCHEMA — what the API returns to the caller
# ─────────────────────────────────────────────────────────────

class ConfigResponse(BaseModel):
    """
    Schema for API responses. This is what callers receive back.
    
    Notice it includes 'id', 'version', 'created_at', 'updated_at'
    — these are generated by the server, not provided by the caller.
    
    Example JSON response:
    {
        "id": 1,
        "service_name": "payment-service",
        "environment": "prod",
        "key": "DB_HOST",
        "value": "payment-db.internal",
        "version": 1,
        "created_at": "2024-01-15T10:30:00Z",
        "updated_at": "2024-01-15T10:30:00Z"
    }
    """

    id: int
    service_name: str
    environment: str
    key: str           # We'll map config_key → key in model_config below
    value: str         # We'll map config_value → value
    version: int
    created_at: datetime
    updated_at: datetime

    # model_config tells Pydantic to read data from SQLAlchemy model objects
    # (not just plain dictionaries)
    model_config = {
        "from_attributes": True,  # Required to work with SQLAlchemy ORM objects
        "populate_by_name": True  # Allow using field aliases
    }

    @classmethod
    def from_orm_model(cls, config) -> "ConfigResponse":
        """
        Custom factory method to convert SQLAlchemy Config object to this schema.
        
        Why needed? Our DB columns are named 'config_key' and 'config_value',
        but our API uses 'key' and 'value'. This method handles the mapping.
        """
        return cls(
            id=config.id,
            service_name=config.service_name,
            environment=config.environment,
            key=config.config_key,
            value=config.config_value,
            version=config.version,
            created_at=config.created_at,
            updated_at=config.updated_at
        )


# ─────────────────────────────────────────────────────────────
# LIST RESPONSE — wraps a list of configs with metadata
# ─────────────────────────────────────────────────────────────

class ConfigListResponse(BaseModel):
    """
    Wraps a list of configs with some useful metadata.
    
    Example:
    {
        "service_name": "payment-service",
        "environment": "prod",
        "count": 3,
        "configs": [ {...}, {...}, {...} ]
    }
    """
    service_name: str
    environment: str
    count: int
    configs: list[ConfigResponse]


# ─────────────────────────────────────────────────────────────
# GENERIC MESSAGE RESPONSE — for simple success/error messages
# ─────────────────────────────────────────────────────────────

class MessageResponse(BaseModel):
    """
    Simple response for operations like delete.
    
    Example:
    {
        "message": "Config deleted successfully",
        "config_id": 5
    }
    """
    message: str
    config_id: Optional[int] = None
